name: Build Workflow
on:
    push:
      tags:
        - '*'

permissions:
    contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -U -r requirements.txt
      - name: Run PyInstaller
        run: |
          python -m PyInstaller toolbox.spec
      - name: Upload Linux Artifact
        uses: ncipollo/release-action@v1
        with:
            allowUpdates: True
            makeLatest: True
            omitBody: True
            omitBodyDuringUpdate: True
            omitNameDuringUpdate: True
            artifacts: "dist/toolbox"
            token: ${{ secrets.GITHUB_TOKEN }}
